### ISSUE TITLE
QB V1 query $IRVAL?* not working, missing attribute get_ir

### ISSUE THREAD

**Issue by martykube** [o-botics/quickbot_bbb#6]
query for the IR values is not working:

debian@beaglebone:~/quickbot_bbb$ sudo ./run.py --rtype quick_v1
Running XBot
Running XBot Program
    Base IP:  192.168.7.1
    Robot IP:  192.168.7.2
    Robot Type:  quick_v1
$IRVAL?*
Shutting down...Done
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/home/debian/quickbot_bbb/xbots/base.py", line 280, in parse_cmd
<type 'exceptions.AttributeError'>: 'QuickBot' object has no attribute 'get_ir'

**Comment by martykube** [comment]
fixed by e071450
